name: 🗂️Create repository
description: Create a git repository
title: "[BUG]: "
labels: ["bug"]
type: Bug
body:
  - type: dropdown
    id: application
    attributes:
      label: "Select application"
      description: "Select the application it will be used as a prefix"
      options:
        - label: "Application1"
          value: "application1"
        - label: "Application2"
          value: "application2"
        - label: "Application3"
          value: "application3"
        - label: "Application4"
          value: "application4"
        - label: "Application5"
          value: "application5"
        - label: "Application6"
          value: "application6"
    validations:
      required: true
  - type: input
    id: repositoryname
    attributes:
      label: Repository name
      description: Name of repeository, use hyphen "-"  as separator.
    validations:
      required: true
