name: 📝Retrospective
description: Create a retrospective
labels: ["retrospective"]
title: "[RETRO]: "
type: epic
body:
  - type: markdown
    attributes:
      value: |
        Use this template to create a retrospective. Create your retrospective items as sub-tasks.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Goal of the sprint
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Give us some additional information on the sprint and a summary of the retro.
