name: ✨Story
description: Request a new story
labels: ["enhancement"]
title: "[FEAT]: "
body:
  - type: markdown
    attributes:
      value: |
        Please make sure this story request hasn't been already submitted by someone by looking through other open/closed issues

  - type: dropdown
    id: project
    attributes:
      label: "Select Project"
      description: "Choose the project to link this issue to."
      options:
        - label: "MileStone planning"
          value: "testingorg401/5"
        - label: "Squad 1 scrum board"
          value: "testingorg401/1"
        - label: "Squad 2 scrum board"
          value: "testingorg401/4"
        - label: "Squad 3 scrum board"
          value: "testingorg401/2"
        - label: "Squad 4 scrum board"
          value: "testingorg401/6"
          
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give us a brief description of the feature or enhancement you would like
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Give us some additional information on the feature request like proposed solutions, links, screenshots, etc.
